name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'pool/**/*.deb'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Generate Packages.gz
        run: |
          mkdir -p dists/stable/main/binary-amd64
          mkdir -p dists/stable/main/binary-i386
          dpkg-scanpackages pool /dev/null | gzip -9c > dists/stable/main/binary-amd64/Packages.gz

      - name: Generate HTML index
        run: |
          echo "<html><body><h1>Package Repository</h1><ul>" > index.html
          find pool -type f -name "*.deb" | while read filepath; do
            filename=$(basename "$filepath")
            echo "<li><a href=\"$filepath\">$filename</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cp -r dists gh-pages/
          cp -r pool gh-pages/
          cp index.html gh-pages/
          cd gh-pages
          git add .
          git commit -m 'Update GitHub Pages with latest packages'
<<<<<<< HEAD
          git push origin gh-pages
=======
          git push origin gh-pages
>>>>>>> a273b9acfb57006adefa3c7b27c200c6b5ae538c
