name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'pool/**/*.deb'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Generate Packages.gz
        run: |
          mkdir -p dists/stable/main/binary-amd64
          mkdir -p dists/stable/main/binary-i386
          dpkg-scanpackages pool /
